name: Build Android Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pegar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configurar Java 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Configurar Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.0
          # Instala também plataformas e ferramentas necessárias
          components: "platform-tools,platforms;android-35,build-tools;35.0.0"

      # 4️⃣ Permissão de execução para gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5️⃣ Limpar e build debug
      - name: Build APK Debug
        run: ./gradlew clean assembleDebug --stacktrace

      # 6️⃣ Fazer upload do APK gerado
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ActivitySend-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk