name: Build Android Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pegar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Configurar Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '35'
          build-tools: '35.0.0'

      # 4️⃣ Criar/Atualizar local.properties
      - name: Create/Update local.properties
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          echo "Created/Updated local.properties:"
          cat local.properties
          if [ -d "/usr/local/lib/android/sdk" ]; then
            echo "SDK found at /usr/local/lib/android/sdk"
            ls -la /usr/local/lib/android/sdk
          else
            echo "ERROR: SDK directory not found at /usr/local/lib/android/sdk!"
            exit 1
          fi
          echo "ANDROID_HOME: /usr/local/lib/android/sdk"
          echo "ANDROID_SDK_ROOT: /usr/local/lib/android/sdk"
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

      # 5️⃣ Cache do Gradle
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 6️⃣ Permissão de execução para gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 7️⃣ Limpar cache do Gradle
      - name: Clean Gradle cache
        run: |
          ./gradlew cleanBuildCache
          rm -rf ~/.gradle/caches

      # 8️⃣ Verificar dependências (debug)
      - name: Check dependencies
        run: ./gradlew app:dependencies > dependencies.txt

      # 9️⃣ Build debug com mais memória e sem daemon
      - name: Build APK Debug
        run: ./gradlew clean assembleDebug --no-daemon --stacktrace
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ORG_GRADLE_PROJECT_org_gradle_jvmargs: "-Xmx4g -Dfile.encoding=UTF-8"

      # 10️⃣ Fazer upload do relatório de dependências (se falhar)
      - name: Upload dependencies report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Dependencies-Report
          path: dependencies.txt

      # 11️⃣ Fazer upload do APK gerado
      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ActivitySend-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk