name: Build Android Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pegar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3️⃣ Configurar Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '35'
          build-tools: '35.0.0'

      # 4️⃣ Criar/Atualizar local.properties
      - name: Create/Update local.properties
        run: |
          echo "sdk.dir=${{ runner.tool_cache }}/Android/sdk" > local.properties
          echo "Created/Updated local.properties:"
          cat local.properties
          ls -la ${{ runner.tool_cache }}/Android/sdk || echo "ERROR: SDK directory not found!"
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "ANDROID_SDK_ROOT