name: Build Android Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pegar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Cache do Gradle (evita downloads desnecessários)
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # 3️⃣ Configurar Java 17
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 4️⃣ Configurar Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: 35.0.0
          components: "platform-tools,platforms;android-35,build-tools;35.0.0"

      # 5️⃣ Permissão de execução para gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 6️⃣ Build debug com mais memória e sem daemon
      - name: Build APK Debug
        run: ./gradlew clean assembleDebug --no-daemon --stacktrace
        env:
          ORG_GRADLE_PROJECT_org_gradle_jvmargs: "-Xmx4g -Dfile.encoding=UTF-8"

      # 7️⃣ Fazer upload do APK gerado
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ActivitySend-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk