name: Build Android Debug APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Baixar o código do repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      # 3️⃣ Instalar Android SDK + Build Tools
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: '35.0.0'
          cmake: '3.22.1'

      # 4️⃣ Criar arquivo local.properties (caso não exista)
      - name: Create local.properties
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          cat local.properties

      # 5️⃣ Garantir permissão de execução para gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 6️⃣ Limpar cache de build anterior
      - name: Clean project
        run: ./gradlew clean

      # 7️⃣ Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.path }}
          ANDROID_HOME: /usr/local/lib/android/sdk
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
          ORG_GRADLE_PROJECT_org_gradle_jvmargs: "-Xmx4g -Dfile.encoding=UTF-8"

      # 8️⃣ Upload do APK gerado
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ActivitySend-Debug-APK
          path: app/build/outputs/apk/debug/app-debug.apk